### ISSUE TITLE
[BUG] Missing the value texts in metadata response for a table

### ISSUE THREAD

**Issue by likp** [CSOIreland/PxStat#253]
**Describe the bug**
The valueTexts element is missing in the response for a table metadata

**To Reproduce**
Use postman to do a HTTP GET on the following url
https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.PxAPIv1/en/30/GEI/TSA05

**Expected behavior**
For each variable to have a valueTexts property containing all value texts. See example  in chapter 4.3 in https://www.scb.se/contentassets/79c32c72783a4f67b202ad3189f921b9/api-description.pdf

**Comment by lorenzobruni** [comment]
@likp 
Hi, can you please attach the document in English? :-)
Is it the same version of this one perhaps? https://www.scb.se/contentassets/79c32c72783a4f67b202ad3189f921b9/api-description.pdf

Thanks

**Comment by lorenzobruni** [comment]
@likp 
the one in red, correct? 
![image](https://user-images.githubusercontent.com/53212047/96583260-56967600-12d4-11eb-89c4-c3097010c200.png)

@neilfromcork 
can you please look after this ASAP?
I think we missed to list the variable names.

**Comment by likp** [comment]
Yes, it is sorry about the link to the Swedish version. It should be updated now.

**Comment by neilfromcork** [comment]
Issue fixed in DEV - ready for test

**Comment by lorenzobruni** [comment]
@likp 
I think it's now fixed, see screenshot from our Dev environment.
Thanks a mill for helping us with your valuable testing 👍 👍 👍 

I did an emergency release in https://data.cso.ie so you and @statgreen can check it out.
Please reopen the issue if something is still wrong.

It will be available in GitHub under the next **Milestone 2.7.0**

Cheers
![image](https://user-images.githubusercontent.com/53212047/96620522-74c59b80-12ff-11eb-8841-ceb42234641b.png)

**Comment by likp** [comment]
Hi, it looks correct now. I tried it in Postman and in Chrome and it looks like I am getting correct answers. I wanted to verify it in PxWin but I get a 500 error when browsing the database which is strange since it worked yesterday. But the problem is probably on our side but I do not have the time to investigate it right now.

**Comment by lorenzobruni** [comment]
@likp 
I have double tested the web-service and is up and running, please see screenshot.
Your code looks good to me... are you still getting the 500 error message from both C# and the Browser?

![image](https://user-images.githubusercontent.com/53212047/99798370-d0ff2380-2b28-11eb-913a-48f5032c6039.png)

By the way, I'm trying to plugin the API into the PxWin configuration, like below, but nothing show up in PxWin... 

Both https://api.scb.se/OV0104/v1/doris/en/ssd/ and https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.PxAPIv1/en/ produce the same json schema... am I missing any other configuration? thanks

```xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<databases>
  <database id="demo_CNMM" type="CNMM" name="CNMM database">
  </database>
   <database id="demo_PX" type="PX" name="PX database">
      <params>
         <path>path_to_Demo_database</path>
      </params>
   </database>
   <database id="ssd_api" type="PXAPI" name="Statistics Sweden API">
      <params>
         <baseUrl>https://api.scb.se/OV0104/v1/doris/{0}/ssd/</baseUrl>
         <supportedLanguages>sv,en</supportedLanguages>
      </params>
   </database>
   <database id="cso_api" type="PXAPI" name="CSO Ireland API">
      <params>
         <baseUrl>https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.PxAPIv1/{0}/</baseUrl>
         <supportedLanguages>en</supportedLanguages>
      </params>
   </database>
</databases>
```

**Comment by likp** [comment]
@lorenzobruni  your config looks correct. Although I still get get Internal Server error from PxWin. Did you managed tro run the code example at https://github.com/CSOIreland/PxStat/issues/253#issuecomment-713351485 at your site. Becuase I still get the Insterna Server error using the HttpClient from C#. 
Hiting the url from the browser of Postman works fine.

**Comment by lorenzobruni** [comment]
@likp Thanks a lot! We found the issue. 
The base layer of the API was expecting to get always the `userAgent `in the response, which of curse is not the case when running from C#. 

We fixed this one into the release 4.3.1 of the [Server API Library](https://github.com/CSOIreland/Server-API-Library) project available at https://github.com/CSOIreland/Server-API-Library/releases/tag/4.3.1

The Library will be merged into the PxStat project during this week.
I'm re-opening this Issue and we can test it again once published.

I keep you posted when ready.

Cheers

**Comment by lorenzobruni** [comment]
@likp 
Hi, we have released the updated code and I have mixed news.

1. If I point to the Test API (test-ws.cso.ie) hosted in our internal web-server then I can browse the database.
```xml
<database id="cso_api" type="PXAPI" name="CSO Test API">
      <params>
         <baseUrl>https://test-ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.PxAPIv1/{0}/</baseUrl>
         <supportedLanguages>en</supportedLanguages>
      </params>
   </database>
```
2. Unfortunately, as soon as I make a table selection, by picking some variables I get this error
![image](https://user-images.githubusercontent.com/53212047/100680615-d3078480-3369-11eb-98da-c69b2dfa334b.png)
3. Instead, if I point to the Live API (ws.cso.ie) which is hosted publicly then I does **NOT** work, I get a blank listing with no error.
4. I have also noticed that I cannot change the `<baseUrl>` without changing also the `<database id="">`. It looks like the database id are retained like in a static class? How do you force the application to refresh the `<baseUrl>`?
5. Are there any logsI can extract and share with you? 

Thanks

**Comment by likp** [comment]
I could be the caching that causes it not to reload. But you could right click on "CSO Test API" and select Reload from the context menu to force a reload.

PXWin uses log4net so check how it is configured in your installation and you will be able to find the config files.

**Comment by lorenzobruni** [comment]
@likp 
Hi, I'm sorry I forgot to close one and to keep you posted!
The data fetching works fine with PxWin, including 1.3 version, see screenshot :-)

Would you consider adding our **Statistics Ireland API** end-point in your **PxWin 1.3** version, together with all the other databases? Please find the XML code for _databases.config_

```xml
   <database id="is_api_ireland" type="PXAPI" name="Statistics Ireland API">
      <params>
         <baseUrl>https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.PxAPIv1/{0}/</baseUrl>
         <supportedLanguages>en,ga</supportedLanguages>
      </params>
   </database>
```


![image](https://user-images.githubusercontent.com/53212047/198249190-af4a4309-e2ea-4509-911e-b61ec47e0a26.png)

**Comment by lorenzobruni** [comment]
Pull request created in PxWin https://github.com/statisticssweden/PxWin/pull/21
